language: python
python: 3.6
env:
  - TOX_ENV=py27-111
  - TOX_ENV=py36-111
# command to install dependencies
install:
  - pip install tox
# command to run tests
script:
  - tox -e $TOX_ENV
# containers
sudo: false

